updated workflow

diff --git a/.github/workflows/push-tests.yml b/.github/workflows/push-tests.yml
--- a/.github/workflows/push-tests.yml
+++ b/.github/workflows/push-tests.yml
@@ -89,7 +89,6 @@ jobs:
         run: |
           npm ci
           npx playwright install --with-deps
-          # npx playwright-merge-html-reports install
           cp src/configs/local.js src/configs/configs.js
           npm run dev&
 
@@ -125,24 +124,36 @@ jobs:
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
         if: failure() && github.ref == 'refs/heads/main'
-
+  
+  wait-for-shards:
+    name: Wait for shards
+    needs: e2e-test # run after shards
+    runs-on: ubuntu-20.04
+    if: success() # only run when all shards have passed
+    # store success output flag for ci job
+    outputs:
+      success: ${{ steps.setoutput.outputs.success }}
+    steps:
+      - id: setoutput
+        run: echo "{success}={true}" >> $GITHUB_OUTPUT
+  
   # https://github.com/myieye/web-languageforge/blob/develop/.github/workflows/e2e-tests.yml
   e2e-result:
-      name: e2e-result
-      if: always()
-      runs-on: ubuntu-latest
-      needs: e2e-test
-      steps:
-        - name: Check result
-          run: |
-            passed="${{ needs.e2e-test.result }}"
-            if [[ $passed == "success" ]]; then
-              echo "Shards passed"
-              exit 0
-            else
-              echo "Shards failed"
-              exit 1
-            fi
+    name: e2e-result
+    if: always()
+    runs-on: ubuntu-latest
+    needs: [e2e-test, wait-for-shards]
+    steps:
+      - name: Check result
+        run: |
+          passed="${{ needs.e2e-test.result }}"
+          if [[ $passed == "success" ]]; then
+            echo "Shards passed"
+            exit 0
+          else
+            echo "Shards failed"
+            exit 1
+          fi
 
   backend-unit-test:
     runs-on: ubuntu-20.04
