last bit

diff --git a/.github/workflows/rdev-update-for-pr.yml b/.github/workflows/rdev-update-for-pr.yml
--- a/.github/workflows/rdev-update-for-pr.yml
+++ b/.github/workflows/rdev-update-for-pr.yml
@@ -296,19 +296,19 @@ jobs:
           retention-days: 30
 
   # # https://github.com/myieye/web-languageforge/blob/develop/.github/workflows/e2e-tests.yml
-  # e2e-test:
-  #   name: e2e-test
-  #   if: always()
-  #   runs-on: ubuntu-latest
-  #   needs: [run-e2e-tests, wait-for-shards]
-  #   steps:
-  #     - name: Check result
-  #       run: |
-  #         passed="${{ needs.run-e2e-tests.result }}"
-  #         if [[ $passed == "success" ]]; then
-  #           echo "Shards passed"
-  #           exit 0
-  #         else
-  #           echo "Shards failed"
-  #           exit 1
-  #         fi
+  e2e-test:
+    name: e2e-test
+    if: always()
+    runs-on: ubuntu-latest
+    needs: [run-e2e-tests, wait-for-shards]
+    steps:
+      - name: Check result
+        run: |
+          passed="${{ needs.run-e2e-tests.result }}"
+          if [[ $passed == "success" ]]; then
+            echo "Shards passed"
+            exit 0
+          else
+            echo "Shards failed"
+            exit 1
+          fi
