debug

diff --git a/.github/workflows/rdev-update-for-pr.yml b/.github/workflows/rdev-update-for-pr.yml
--- a/.github/workflows/rdev-update-for-pr.yml
+++ b/.github/workflows/rdev-update-for-pr.yml
@@ -257,6 +257,17 @@ jobs:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
         if: failure() && github.ref == 'refs/heads/main'
 
+  wait-for-shards:
+    needs: run-e2e-tests # run after shards
+    runs-on: ubuntu-22.04
+    if: success() # only run when all shards have passed
+    # store success output flag for ci job
+    outputs:
+      success: ${{ steps.setoutput.outputs.success }}
+    steps:
+      - id: setoutput
+        run: echo "{success}={true}" >> $GITHUB_OUTPUT
+
   merge-playwright-reports:
     # Merge reports after playwright-tests, even if some shards have failed
     if: always()
@@ -290,6 +301,24 @@ jobs:
           name: html-report--attempt-${{ github.run_attempt }}
           path: /home/runner/work/single-cell-data-portal/single-cell-data-portal/frontend/playwright-report
           retention-days: 30
+
+  # https://github.com/myieye/web-languageforge/blob/develop/.github/workflows/e2e-tests.yml
+  e2e-test:
+    if: always()
+    name: e2e-test
+    runs-on: ubuntu-latest
+    needs: [wait-for-shards, run-e2e-tests]
+    steps:
+      - name: Check result
+        run: |
+          passed="${{ needs.run-e2e-tests.result }}"
+          if [[ $passed == "success" ]]; then
+            echo "Shards passed"
+            exit 0
+          else
+            echo "Shards failed"
+            exit 1
+          fi
 
   e2e-logged-in-test:
     timeout-minutes: 30
